INSERT INTO countries (id, iso, name)
VALUES (1, 'AF', 'Afganistán'),
    (2, 'AX', 'Islas Gland'),
    (3, 'AL', 'Albania'),
    (4, 'DE', 'Alemania'),
    (5, 'AD', 'Andorra'),
    (6, 'AO', 'Angola'),
    (7, 'AI', 'Anguilla'),
    (8, 'AQ', 'Antartida'),
    (9, 'AG', 'Antigua y Barbuda'),
    (10, 'AN', 'Antillas Holandesas');
INSERT INTO countries (id, iso, name)
VALUES (11, 'SA', 'Arabia Saud?'),
    (12, 'DZ', 'Argelia'),
    (13, 'AR', 'Argentina'),
    (14, 'AM', 'Armenia'),
    (15, 'AW', 'Aruba'),
    (16, 'AU', 'Australia'),
    (17, 'AT', 'Austria'),
    (18, 'AZ', 'Azerbaiy?n'),
    (19, 'BS', 'Bahamas'),
    (20, 'BH', 'Bahr?in');
INSERT INTO countries (id, iso, name)
VALUES (21, 'BD', 'Bangladesh'),
    (22, 'BB', 'Barbados'),
    (23, 'BY', 'Bielorrusia'),
    (24, 'BE', 'B?lgica'),
    (25, 'BZ', 'Belice'),
    (26, 'BJ', 'Benin'),
    (27, 'BM', 'Bermudas'),
    (28, 'BT', 'Bhut?n'),
    (29, 'BO', 'Bolivia'),
    (30, 'BA', 'Bosnia y Herzegovina');
INSERT INTO countries (id, iso, name)
VALUES (31, 'BW', 'Botsuana'),
    (32, 'BV', 'Isla Bouvet'),
    (33, 'BR', 'Brasil'),
    (34, 'BN', 'Brun?i'),
    (35, 'BG', 'Bulgaria'),
    (36, 'BF', 'Burkina Faso'),
    (37, 'BI', 'Burundi'),
    (38, 'CV', 'Cabo Verde'),
    (39, 'KY', 'Islas Caim?n'),
    (40, 'KH', 'Camboya');
INSERT INTO countries (id, iso, name)
VALUES (41, 'CM', 'Camer?n'),
    (42, 'CA', 'Canad?'),
    (43, 'CF', 'Rep?blica Centroafricana'),
    (44, 'TD', 'Chad'),
    (45, 'CZ', 'Rep?blica Checa'),
    (46, 'CL', 'Chile'),
    (47, 'CN', 'China'),
    (48, 'CY', 'Chipre'),
    (49, 'CX', 'Isla de Navidad'),
    (50, 'VA', 'Ciudad del Vaticano');
INSERT INTO countries (id, iso, name)
VALUES (51, 'CC', 'Islas Cocos'),
    (52, 'CO', 'Colombia'),
    (53, 'KM', 'Comoras'),
    (54, 'CD', 'Rep?blica Democr?tica del Congo'),
    (55, 'CG', 'Congo'),
    (56, 'CK', 'Islas Cook'),
    (57, 'KP', 'Corea del Norte'),
    (58, 'KR', 'Corea del Sur'),
    (59, 'CI', 'Costa de Marfil'),
    (60, 'CR', 'Costa Rica');
INSERT INTO countries (id, iso, name)
VALUES (61, 'HR', 'Croacia'),
    (62, 'CU', 'Cuba'),
    (63, 'DK', 'Dinamarca'),
    (64, 'DM', 'Dominica'),
    (65, 'DO', 'Rep?blica Dominicana'),
    (66, 'EC', 'Ecuador'),
    (67, 'EG', 'Egipto'),
    (68, 'SV', 'El Salvador'),
    (69, 'AE', 'Emiratos ?rabes Unidos'),
    (70, 'ER', 'Eritrea');
INSERT INTO countries (id, iso, name)
VALUES (71, 'SK', 'Eslovaquia'),
    (72, 'SI', 'Eslovenia'),
    (73, 'ES', 'España'),
    (74, 'UM', 'Islas ultramarinas de Estados Unidos'),
    (75, 'US', 'Estados Unidos'),
    (76, 'EE', 'Estonia'),
    (77, 'ET', 'Etiop?a'),
    (78, 'FO', 'Islas Feroe'),
    (79, 'PH', 'Filipinas'),
    (80, 'FI', 'Finlandia');
INSERT INTO countries (id, iso, name)
VALUES (81, 'FJ', 'Fiyi'),
    (82, 'FR', 'Francia'),
    (83, 'GA', 'Gab?n'),
    (84, 'GM', 'Gambia'),
    (85, 'GE', 'Georgia'),
    (
        86,
        'GS',
        'Islas Georgias del Sur y Sandwich del Sur'
    ),
    (87, 'GH', 'Ghana'),
    (88, 'GI', 'Gibraltar'),
    (89, 'GD', 'Granada'),
    (90, 'GR', 'Grecia');
INSERT INTO countries (id, iso, name)
VALUES (91, 'GL', 'Groenlandia'),
    (92, 'GP', 'Guadalupe'),
    (93, 'GU', 'Guam'),
    (94, 'GT', 'Guatemala'),
    (95, 'GF', 'Guayana Francesa'),
    (96, 'GN', 'Guinea'),
    (97, 'GQ', 'Guinea Ecuatorial'),
    (98, 'GW', 'Guinea-Bissau'),
    (99, 'GY', 'Guyana'),
    (100, 'HT', 'Hait?');
INSERT INTO countries (id, iso, name)
VALUES (101, 'HM', 'Islas Heard y McDonald'),
    (102, 'HN', 'Honduras'),
    (103, 'HK', 'Hong Kong'),
    (104, 'HU', 'Hungr?a'),
    (105, 'IN', 'India'),
    (106, 'ID', 'Indonesia'),
    (107, 'IR', 'Ir?n'),
    (108, 'IQ', 'Iraq'),
    (109, 'IE', 'Irlanda'),
    (110, 'IS', 'Islandia');
INSERT INTO countries (id, iso, name)
VALUES (111, 'IL', 'Israel'),
    (112, 'IT', 'Italia'),
    (113, 'JM', 'Jamaica'),
    (114, 'JP', 'Jap?n'),
    (115, 'JO', 'Jordania'),
    (116, 'KZ', 'Kazajst?n'),
    (117, 'KE', 'Kenia'),
    (118, 'KG', 'Kirguist?n'),
    (119, 'KI', 'Kiribati'),
    (120, 'KW', 'Kuwait');
INSERT INTO countries (id, iso, name)
VALUES (121, 'LA', 'Laos'),
    (122, 'LS', 'Lesotho'),
    (123, 'LV', 'Letonia'),
    (124, 'LB', 'L?bano'),
    (125, 'LR', 'Liberia'),
    (126, 'LY', 'Libia'),
    (127, 'LI', 'Liechtenstein'),
    (128, 'LT', 'Lituania'),
    (129, 'LU', 'Luxemburgo'),
    (130, 'MO', 'Macao');
INSERT INTO countries (id, iso, name)
VALUES (131, 'MK', 'ARY Macedonia'),
    (132, 'MG', 'Madagascar'),
    (133, 'MY', 'Malasia'),
    (134, 'MW', 'Malawi'),
    (135, 'MV', 'Maldivas'),
    (136, 'ML', 'Mal?'),
    (137, 'MT', 'Malta'),
    (138, 'FK', 'Islas Malvinas'),
    (139, 'MP', 'Islas Marianas del Norte'),
    (140, 'MA', 'Marruecos');
INSERT INTO countries (id, iso, name)
VALUES (141, 'MH', 'Islas Marshall'),
    (142, 'MQ', 'Martinica'),
    (143, 'MU', 'Mauricio'),
    (144, 'MR', 'Mauritania'),
    (145, 'YT', 'Mayotte'),
    (146, 'MX', 'M?xico'),
    (147, 'FM', 'Micronesia'),
    (148, 'MD', 'Moldavia'),
    (149, 'MC', 'M?naco'),
    (150, 'MN', 'Mongolia');
INSERT INTO countries (id, iso, name)
VALUES (151, 'MS', 'Montserrat'),
    (152, 'MZ', 'Mozambique'),
    (153, 'MM', 'Myanmar'),
    (154, 'NA', 'Namibia'),
    (155, 'NR', 'Nauru'),
    (156, 'NP', 'Nepal'),
    (157, 'NI', 'Nicaragua'),
    (158, 'NE', 'N?ger'),
    (159, 'NG', 'Nigeria'),
    (160, 'NU', 'Niue');
INSERT INTO countries (id, iso, name)
VALUES (161, 'NF', 'Isla Norfolk'),
    (162, 'NO', 'Noruega'),
    (163, 'NC', 'Nueva Caledonia'),
    (164, 'NZ', 'Nueva Zelanda'),
    (165, 'OM', 'Om?n'),
    (166, 'NL', 'Pa?ses Bajos'),
    (167, 'PK', 'Pakist?n'),
    (168, 'PW', 'Palau'),
    (169, 'PS', 'Palestina'),
    (170, 'PA', 'Panam?');
INSERT INTO countries (id, iso, name)
VALUES (171, 'PG', 'Pap?a Nueva Guinea'),
    (172, 'PY', 'Paraguay'),
    (173, 'PE', 'Per?'),
    (174, 'PN', 'Islas Pitcairn'),
    (175, 'PF', 'Polinesia Francesa'),
    (176, 'PL', 'Polonia'),
    (177, 'PT', 'Portugal'),
    (178, 'PR', 'Puerto Rico'),
    (179, 'QA', 'Qatar'),
    (180, 'GB', 'Reino Unido');
INSERT INTO countries (id, iso, name)
VALUES (181, 'RE', 'Reuni?n'),
    (182, 'RW', 'Ruanda'),
    (183, 'RO', 'Rumania'),
    (184, 'RU', 'Rusia'),
    (185, 'EH', 'Sahara Occidental'),
    (186, 'SB', 'Islas Salom?n'),
    (187, 'WS', 'Samoa'),
    (188, 'AS', 'Samoa Americana'),
    (189, 'KN', 'San Crist?bal y Nevis'),
    (190, 'SM', 'San Marino');
INSERT INTO countries (id, iso, name)
VALUES (191, 'PM', 'San Pedro y Miquel?n'),
    (192, 'VC', 'San Vicente y las Granadinas'),
    (193, 'SH', 'Santa Helena'),
    (194, 'LC', 'Santa Luc?a'),
    (195, 'ST', 'Santo Tom? y Pr?ncipe'),
    (196, 'SN', 'Senegal'),
    (197, 'CS', 'Serbia y Montenegro'),
    (198, 'SC', 'Seychelles'),
    (199, 'SL', 'Sierra Leona'),
    (200, 'SG', 'Singapur');
INSERT INTO countries (id, iso, name)
VALUES (201, 'SY', 'Siria'),
    (202, 'SO', 'Somalia'),
    (203, 'LK', 'Sri Lanka'),
    (204, 'SZ', 'Suazilandia'),
    (205, 'ZA', 'Sud?frica'),
    (206, 'SD', 'Sud?n'),
    (207, 'SE', 'Suecia'),
    (208, 'CH', 'Suiza'),
    (209, 'SR', 'Surinam'),
    (210, 'SJ', 'Svalbard y Jan Mayen');
INSERT INTO countries (id, iso, name)
VALUES (211, 'TH', 'Tailandia'),
    (212, 'TW', 'Taiw?n'),
    (213, 'TZ', 'Tanzania'),
    (214, 'TJ', 'Tayikist?n'),
    (
        215,
        'IO',
        'Territorio Brit?nico del Oc?ano ?ndico'
    ),
    (216, 'TF', 'Territorios Australes Franceses'),
    (217, 'TL', 'Timor Oriental'),
    (218, 'TG', 'Togo'),
    (219, 'TK', 'Tokelau'),
    (220, 'TO', 'Tonga');
INSERT INTO countries (id, iso, name)
VALUES (221, 'TT', 'Trinidad y Tobago'),
    (222, 'TN', 'T?nez'),
    (223, 'TC', 'Islas Turcas y Caicos'),
    (224, 'TM', 'Turkmenist?n'),
    (225, 'TR', 'Turqu?a'),
    (226, 'TV', 'Tuvalu'),
    (227, 'UA', 'Ucrania'),
    (228, 'UG', 'Uganda'),
    (229, 'UY', 'Uruguay'),
    (230, 'UZ', 'Uzbekist?n');
INSERT INTO countries (id, iso, name)
VALUES (231, 'VU', 'Vanuatu'),
    (232, 'VE', 'Venezuela'),
    (233, 'VN', 'Vietnam'),
    (234, 'VG', 'Islas V?rgenes Brit?nicas'),
    (235, 'VI', 'Islas V?rgenes de los Estados Unidos'),
    (236, 'WF', 'Wallis y Futuna'),
    (237, 'YE', 'Yemen'),
    (238, 'DJ', 'Yibuti'),
    (239, 'ZM', 'Zambia'),
    (240, 'ZW', 'Zimbabue');